#!/usr/bin/env node

import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { dirname, relative, resolve } from "node:path";

const REQUIRED_NODE_MAJOR = 24;

function usage() {
  console.log(`Claude Web2 cross-platform setup

Usage:
  npm run setup
  npm run setup -- --output path/to/.env
  npm run setup -- --force

Options:
  --output <path>  Write the environment file to this path (default: .env)
  --force          Replace an existing output file
  --quiet          Do not print the generated bootstrap password
  --help           Show this help

The generated administrator password is printed once. Save it before starting the service.`);
}

function parseArgs(argv) {
  const options = { output: ".env", force: false, quiet: false, help: false };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--help" || argument === "-h") {
      options.help = true;
    } else if (argument === "--force") {
      options.force = true;
    } else if (argument === "--quiet") {
      options.quiet = true;
    } else if (argument === "--output") {
      const value = argv[index + 1];
      if (!value || value.startsWith("--")) throw new Error("--output requires a path");
      options.output = value;
      index += 1;
    } else {
      throw new Error(`Unknown option: ${argument}`);
    }
  }
  return options;
}

function assertSupportedNode() {
  const major = Number.parseInt(process.versions.node.split(".")[0] ?? "0", 10);
  if (!Number.isInteger(major) || major < REQUIRED_NODE_MAJOR) {
    throw new Error(`Node.js ${REQUIRED_NODE_MAJOR}+ is required; current version is ${process.versions.node}`);
  }
}

function displayPath(filePath) {
  const localPath = relative(process.cwd(), filePath);
  return localPath && !localPath.startsWith("..") ? localPath : filePath;
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  if (options.help) {
    usage();
    return;
  }

  assertSupportedNode();
  const outputPath = resolve(process.cwd(), options.output);
  if (existsSync(outputPath) && !options.force) {
    throw new Error(`${displayPath(outputPath)} already exists; use --force only if you intend to replace it`);
  }

  const masterKey = `base64:${randomBytes(32).toString("base64")}`;
  const adminPassword = randomBytes(24).toString("base64url");
  const contents = [
    "# Generated by npm run setup. Keep this file private and out of version control.",
    `CW2_MASTER_KEY=${masterKey}`,
    `CW2_ADMIN_PASSWORD=${adminPassword}`,
    "CW2_ADMIN_USERNAME=admin",
    "",
    "# Local Node.js listener. Containers override this to 0.0.0.0 internally.",
    "CW2_HOST=127.0.0.1",
    "CW2_PORT=8787",
    "CW2_DATA_DIR=./data",
    "",
    "# Docker host publishing address. Set to 0.0.0.0 only when a firewall or HTTPS proxy protects it.",
    "CW2_BIND_ADDRESS=127.0.0.1",
    "CW2_TRUST_PROXY=false",
    "CW2_SECURE_COOKIES=auto",
    "CW2_ALLOWED_ORIGINS=",
    "CW2_PUBLIC_URL=",
    "CW2_LOG_LEVEL=info",
    "",
  ].join("\n");

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, contents, {
    encoding: "utf8",
    flag: options.force ? "w" : "wx",
    mode: 0o600,
  });
  if (process.platform !== "win32") chmodSync(outputPath, 0o600);

  console.log(`Created ${displayPath(outputPath)} for ${process.platform}/${process.arch}.`);
  if (!options.quiet) {
    console.log("\nBootstrap administrator (shown once):");
    console.log("  username: admin");
    console.log(`  password: ${adminPassword}`);
  }
  console.log("\nNext: npm run doctor && npm run build && npm start");
  console.log("After the first successful login, remove CW2_ADMIN_PASSWORD from the runtime environment.");
}

try {
  main();
} catch (error) {
  console.error(`Setup failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exitCode = 1;
}
